# Generated by Django 4.0.3 on 2022-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
