# Generated by Django 4.0.3 on 2022-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile_remove_skill_user_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
