# Generated by Django 4.0.3 on 2022-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('Flask', 'Flask'), (None, '없음')], max_length=100),
        ),
    ]
