# Generated by Django 4.0.3 on 2022-03-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_profile_img_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_url',
            new_name='img',
        ),
    ]
