# Generated by Django 4.0.3 on 2022-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.URLField(default='https://png.clipart.me/istock/previews/9349/93493545-people-icon.jpg', max_length=250),
        ),
    ]
