# Generated by Django 4.0.3 on 2022-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.TextField()),
                ('user_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
