# Generated by Django 4.0.3 on 2022-04-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
