# Generated by Django 4.0.3 on 2022-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarkapp", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "article"), name="unique_bookmark"
            ),
        ),
    ]
