# Generated by Django 4.0.3 on 2022-03-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likeapp", "0005_datcle_like_count"),
        ("bookmarkapp", "0002_bookmark_unique_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="article",
            field=models.ForeignKey(
                db_column="article",
                on_delete=django.db.models.deletion.CASCADE,
                to="likeapp.post",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                on_delete=django.db.models.deletion.CASCADE,
                to="likeapp.author",
            ),
        ),
    ]
