# Generated by Django 4.0.3 on 2022-03-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
    ]
