# Generated by Django 4.0.3 on 2022-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
