# Generated by Django 4.0.3 on 2022-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_alter_articlehits_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
