# Generated by Django 4.0.3 on 2022-03-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_like_cnt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
