# Generated by Django 4.0.3 on 2022-03-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likeapp', '0001_initial'),
        ('articleapp', '0002_article_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelikes',
            name='article',
            field=models.ForeignKey(db_column='article', on_delete=django.db.models.deletion.CASCADE, to='articleapp.article'),
        ),
        migrations.AddField(
            model_name='articlelikes',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
