# Generated by Django 4.0.3 on 2022-03-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelikes',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='likeapp.author'),
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='likeapp.author'),
        ),
    ]
