# Generated by Django 4.0.3 on 2022-03-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likeapp", "0003_alter_articlelikes_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("like_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="articlelikes",
            name="article",
            field=models.ForeignKey(
                db_column="article",
                on_delete=django.db.models.deletion.CASCADE,
                to="likeapp.post",
            ),
        ),
    ]
