# Generated by Django 4.0.3 on 2022-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likeapp", "0004_post_alter_articlelikes_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="datcle",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
